### ISSUE TITLE
Status not updating

### ISSUE THREAD

**Issue by bljarisch** [tavicu/homebridge-samsung-tizen#10]
I wanted to add my Samsung TV to an automation in HomeKit, so my lights dim when the TV is turned on, however, when the TV is switched on by remote it does not update to "ON" in HomeKit, therefore the automation does not work.  Is it possible to have its status updated immediately?  Thank you for your work on this!

**Comment by tavicu** [comment]
Hi,

Unfortunately this is not possible because of the Samsung API which is very very dumb. It allows us only to send commands to the TV and nothing more.

Right now to check if the TV is ON i am using a method to check if the IP address is active. And this method is called only when the HomeKit decide it needs to update the status.

The only method to do it is by setting an interval and check every second (or a few seconds) if the TV is ON. But it isn't a clean method but will do the trick. If you want i can implement it :)

**Comment by bljarisch** [comment]
Eh, if it is not a clean method and you think it may cause more issues then it may not be worth it.  I can do what I am trying to do by adding each of my harmony activities to an automation with the lights, but I was wanting to just do it with one automation, since switching between activities seems to be causing issues.  I will keep coming back here for any updates you might add.  Thank you for the quick reply!
