### ISSUE TITLE
[BUG] Switches changing room

### ISSUE THREAD

**Issue by marithpl** [tavicu/homebridge-samsung-tizen#103]
I’ve updated to 3.1.4 and i have problem with switches. Now I cannot set a room for each switch. Now all switches are assigne to one room.

**Comment by tavicu** [comment]
Homebridge or other plugin from it doesn't have anything to do with switch settings! Try force closing the Home app then edit the settings of the switch!

**Comment by marithpl** [comment]
That happend after plugin update to 3.1.4 Here is a screen recording:
https://we.tl/t-RQbPSUuoxu

Is there any command to back to 3.1.0 ?

**Comment by tavicu** [comment]
This happens because now the switches are linked to the main tv instead of being an independent accessory!

Right now it will remain as it is because this is a pre-release for the next major version where each TV will work as a Bridge instead of accessory!

This change is made to allow multiple TV's on the same Homebridge instance.
HomeKit doesn't support multiple TV's on the same bridge.

If you do wish to downgrade you can do it! But i don't recommend it since you will loose new features and bug fixes! 
`sudo npm install -g --unsafe-perm homebridge-samsung-tizen@3.1.0`

**Comment by marithpl** [comment]
Ok, I will live with that for a while. Do you know when will publish fix for it with bridge TV?

In previous version of plugin you add delay option. Is it avaliable in 3.0 plugin? I didn't test it because I waited for homekit TV integration.
(https://github.com/tavicu/homebridge-samsung-tizen/issues/35)

**Comment by tavicu** [comment]
> Ok, I will live with that for a while. Do you know when will publish fix for it with bridge TV?

That release will not "fix" this since it's working on the same principle. Right now there is only one main accessory and switches are linked to it. 
This is because when each TV will become a Bridge you will have to add it in the Home App like you add the Homebridge. Having separated accessories means you will have to add each accessory instead of adding only the TV and then the switches will be added automatically.

> In previous version of plugin you add delay option. Is it avaliable in 3.0 plugin? I didn't test it because I waited for homekit TV integration.

Since you where the only one asking this i didn't implemented it because it will require to change the structure of config file. First it will be more complicated and second, it will not be backward compatible with previous versions. Meaning that everybody needs to update config file when updating the plugin.

And that's something i want to avoid :)

**Comment by MarkBarbieri** [comment]
I perform a delay by using an undefined key (I just called it pause).  It causes an additional delay that would normally occur during keypresses.  I expect you could also use *1s for a timed delay.
```
"command": ["KEY_MENU","PAUSE*3","KEY_DOWN","KEY_ENTER"]
```
This seems to work fine.
