### ISSUE TITLE
Feature Request: add TV trough default Homebridge config

### ISSUE THREAD

**Issue by NathanAMiller** [tavicu/homebridge-samsung-tizen#115]
[Homebridge UI](https://github.com/oznu/homebridge-config-ui-x/releases) latest update support "Television" accessories. I have a LG TV and use this plugin:
https://github.com/merdok/homebridge-webos-tv

By using that, TV automatically showed up in Homebridge accessories in UI also in Homekit.

![image](https://user-images.githubusercontent.com/51482347/59357080-65176980-8d3f-11e9-89c5-e1efb3b1e81b.png)

And no need to set it up separately trough Homekit.

I'm not sure what method they use, but it would be nice if you could add support of this feature.

**Comment by tavicu** [comment]
Hi. 

This is not a feature, it's how it should work! HomeKit expects only one TV per bridge (and it makes sense)! That's why is this implementation where you have to add the TV. Every TV is declared like a new bridge.

Unfortunately config-ui-x don't know how to treat external accessories (like TV's are declared in my plugin).
The owner of LG plugin did not updated his to the correct implementation, that's why it's shown in config-ui.

**Comment by NathanAMiller** [comment]
Thanks for reply. So with that solution we can have only ONE television in Homebrige bridge. Right?

**Comment by tavicu** [comment]
> Thanks for reply. So with that solution we can have only ONE television in Homebrige bridge. Right?

They will work in the Home app but you will not be able to control them from Remote Control for example :)

And who knows what Apple will integrate in the future releases.

So the correct way is how my plugin is integrated. Every TV to be a separate bridge :)

**Comment by NathanAMiller** [comment]
So, is there anyway to have the TV bridge in Node-Red (through: https://www.npmjs.com/package/hap-nodered)
