### ISSUE TITLE
TV always requests to grant the control to TV/Smart Device

### ISSUE THREAD

**Issue by monsterciattolo** [tavicu/homebridge-samsung-tizen#119]
Hi,
i've already disable the notification as below but i get the request often.

- TV is always asking for permissions
On TV go to Settings - General - External Device Manager - Device Connection Manager and set Access Notification to Off.

Probably to every homebridge reboot.
If i don't allow the control, i cannot use TV with homebridge.
Also i have many devices called Smart Device or TV in allowed device on samsung TV.

TV Firmware 1270.3 - last avaiable - but i got the same behivour with previous version.

Could you help me?

Thanks in advice

**Comment by mafyata** [comment]
My setting in tv is set to “ask once” and don’t have a problem. My tv is ue50mu6102 with 1270.3 firmware. Do you use latest plugin version? I have the same problem with older version.

**Comment by monsterciattolo** [comment]
i'm using version homebridge-samsung-tizen v4.0.4

**Comment by mafyata** [comment]
Yes , I am using same version

**Comment by mafyata** [comment]
Here is my config
![C7763DD0-C44D-4DEC-BAA4-AE28DF3C3464](https://user-images.githubusercontent.com/48009267/59784435-16cc1280-92cb-11e9-9255-58245551afcd.jpeg)

**Comment by monsterciattolo** [comment]
This is the mine

        {
            "platform": "SamsungTizen",
            "inputs": [
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "11101200001"
                },
                {
                    "name": "Prime Video",
                    "type": "app",
                    "value": "3201512006785"
                },
                {
                    "name": "YouTube",
                    "type": "app",
                    "value": "111299001912"
                }
            ],
            "devices": [
                {
                    "name": "TV",
                    "ip": "192.168.188.20",
                    "mac": "9C:8C:6E:8A:65:DF"
                }
            ]
        },

**Comment by tavicu** [comment]
Can you start homebridge in debug mode and post here what you get in the logs when you click Allow?

**Comment by monsterciattolo** [comment]
I've done but i don't see any logs about plugin in homebridge.log file.
Now in my TV i have 2 devices from homebridge: Smart Device and TV allowed.

**Comment by tavicu** [comment]
I will push a version tomorrow with more debug logs and see if we can find an answer :)
I'll "ping" you when i'll make the release

**Comment by tavicu** [comment]
@monsterciattolo Sorry for the late response. Had some medical problems.
I have pushed a new version which logs every answer from TV.

Please update then start the homebridge in debug mode and let me know what the TV returns when you see the popup and when you click Allow. Thanks

**Comment by monsterciattolo** [comment]
@tavicu thanks for your time.
I did the operation but the log is very big so i removed extra information about other plugins.

[homebridge_tv.log](https://github.com/tavicu/homebridge-samsung-tizen/files/3352255/homebridge_tv.log)

**Comment by tavicu** [comment]
From what i can see the TV returns the token when it pairs.

I will make a version with multiple debugs and come back with instructions on how to run it!
But starting from tomorrow. I need to carry my laptop home so i can test it :P

**Comment by greensouth** [comment]
Hi @tavicu hope you are ok!

Other thing I've seen is that sometimes, if you turn the TV ON with the remote, the state doesn't update by itself until opening the Home app.

It's strange, I changed the refresh time several times, and it does it some times and other simply not.

I know because I have a rule which turns the rear speakers ON when the TV is switched ON and sometimes it simply isn't triggered when used the remote control.

I have no idea of what is happening there :P

**Comment by shmoussa** [comment]
Hello - I'm also running into the exact same issue. Latest TV firmware and version of this plugin. My Device List on the TV keeps growing, after each prompt asking me to click Allow (despite the setting for prompting being set to Off).

If I can help debug / figure this out, please send me instructions.

**Comment by tavicu** [comment]
Hei! I have managed to make an update.
There are some logs to check if the token is saved and used on the future requests.

So, here are the steps.

1. First you need to remove the `samsung-tizen.json` file from `accessories`. The accessories folder is where your `config.json` of homebridge is. I will give an example of command but the folder may be different. For docker the accessories folder is where docker instance was created.
`rm -rf ~/.homebridge/accessories/samsung-tizen.json`
2. Install the debug branch of the plugin. `npm install -g --unsafe-perm git://github.com/tavicu/homebridge-samsung-tizen.git#debug`.
Again, for Docker you need to edit `package.json` and at `dependencies` to change `"homebridge-samsung-tizen": "^4.0.5"` with `"homebridge-samsung-tizen": "git://github.com/tavicu/homebridge-samsung-tizen.git#debug"`
Then i think you need to run the `docker-compose pull` and then start the instance again.
3. Check the console for logs. All the logs will be without the timestamp. Example of debugs: `Storage init {...}`, `Device init {...}`, `Check pairing, token: ...`, and so on.
4. Click Allow on the TV.
5. Save the logs (one).
6. Restart the homebridge instance
7. Click Allow on TV if it ask again.
8. Save the logs (two).
9. Tell me the logs separated (one) and (two).

What i want to achieve is to see if the token is saved and used after that. The first run of the server will be without a token (since we removed `samsung-tizen.json`) and it should ask to Pair. The second run of the server should already have the token and use it. :)

**Comment by tavicu** [comment]
@greensouth I will take a look and see if it's something wrong in the code :)

**Comment by shmoussa** [comment]
Hi. I installed per the instructions yesterday and so far, so good (fingers crossed). It only asked me once to Allow, as expected. I'm not sure if it was whatever changes you made for 4.0.5 or if it's because your instructions made me realize that samsung-tizen.json existed and was important (I previously had a script which deleted the entire Accessories homebridge folder on reboot which helped resolve an unrelated homebridge issue - I've now modified the script to ignore the specific JSON). Either way though, thank you. Hope it also gets resolved for the original poster.

**Comment by monsterciattolo** [comment]
I followed me too the instruction and....wow.....tv is not asking again any request after the first confermation!

**Comment by tavicu** [comment]
@shmoussa yeah, the samsung-tizen.json file is important! There is saved the token from tv for future uses.

@monsterciattolo it may be possible that was a permissions problem and Homebridge didn't had permissions to write that file :)

Glad it worked out well!

**Comment by Hochiss** [comment]
@tavicu @mafyata where to find description for KEY_HDMI of the complete commands/switchs/inputs list, please?

**Comment by mafyata** [comment]
In wiki
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Commands
