### ISSUE TITLE
Change to LiveTV input on Samsung series 2018 (Q8)

### ISSUE THREAD

**Issue by medicus07** [tavicu/homebridge-samsung-tizen#125]
Any idea how to change to LiveTV on 2018 series (Q8)...
SELECT-> LEFT*3 -> ENTER does not work...

Thanks a lot!

**Comment by tavicu** [comment]
Hi,

Check on your remote what are the steps to select LiveTV.
`"KEY_SOURCE", "KEY_LEFT*3", "KEY_ENTER"` just simulate opening the source popup. Then left 3 times (works for me because i have LiveTV and two HDMIs

**Comment by medicus07** [comment]
the new gen Samsung tvs only have the smart remote control... you only have an home button

on the bottom of the screen appear all apps in a row. dependent on which app is opened you have to go one, two, three, ... position left or right to open LiveTV.

**Comment by tavicu** [comment]
Try to play with the commands. First put only KEY_SOURCE and see what happens wand what opens, and so on!

**Comment by medicus07** [comment]
I got it...

KEY_SOURCE -> KEY_UP -> KEY_ENTER

Thank you so much!

**Comment by davipt** [comment]
On my 2017 QE6 I've used the sample instructions to use the KEY_SOURCE, which opens the list of sources, above the list of apps, then KEY_LEFT*5 to make sure the selection goes all the way to the left (even if it beeps because it can't go further left), and then one option for KEY_RIGHT*n for each source, as fortunately the source list is constant ("antenna", HDMI1, ... HDMI4)
