### ISSUE TITLE
PIN Support Group Issue

### ISSUE THREAD

**Issue by aspearman** [tavicu/homebridge-samsung-tizen#136]
It seems lots of people would like to see PIN support as shown in these issues:
* #12 and [comment](https://github.com/tavicu/homebridge-samsung-tizen/issues/12#issuecomment-419179810)
* #29 
* #41 and [comment](https://github.com/tavicu/homebridge-samsung-tizen/issues/41#issuecomment-452778119)
* #65 
* #71 
* #74 
* #85 
* #87 

There is [a repository](https://github.com/taherkaraki/homebridge-homesung-tv) to support H and J models, but it's gone through a few owners/forks recently and seems dead. It doesn't publish an `npm` package so it can't be used. 

You've also recommended [this repository](https://github.com/tdudek/samsung-remote-models-2014-and-newer) to test if the model needs a PIN but even that repository seems dead. Regardless, it seems from the number of issues on this repo that a lot of users have newer TVs that require PINs. 

I tried seeing if I could add PIN support to this repo myself but I'm not sure how to actually run and test this software, or the general architecture of the repo. I did see that you attempted to add PIN support yourself early on [here](https://github.com/tavicu/homebridge-samsung-tizen/issues/12#issuecomment-419521062).

Would you mind please adding support for PIN? I'm more than happy to test it with a model `UN65JS850DF` TV. What would you need from me to add this feature?

If you don't want to support it right now, could you please leave this issue open so that others who try to use this repo see the PIN issue.

**Comment by tavicu** [comment]
Hi Andrew,

I do have an idea how to implement the PIN method but unfortunately it's very hard to develop.
I will have to make an external script that make the pairing and return the PIN then change the plugin to support and work with that PIN.

It doesn't sound very hard! But not having a TV where i can test and develop makes it! Because i will always have to ask someone else to test it and to make adjustments! 
Developing blind a feature like this is very hard!

But let's say someone helps me with testing and api responses, there are many hours of development (I'm estimating around two weeks after work including weekends) and doing this it's not worth it!

**Comment by MBarti** [comment]
I'd be very happy to help with testing, if needed. UE65JU6500.

**Comment by MBarti** [comment]
@aspearman alternatively, we could try and update the Homesung plugin to the new "remote" capabilities. It shouldn't be that hard based on other plugins I've seen, though I don't code.

Someone forked it here: https://github.com/kkapitan/homebridge-homesung/compare/master...dariusrosendahl:master and basically by changing 1 line in the code it shows up as the TV remote, but still crashes after pressing some buttons on it. Maybe it's an easy fix?

Looking at some other plugins - some of them are just 1 page of code and that's it, e.g. https://github.com/arnif/homebridge-sony-television/blob/master/index.js

**Comment by aspearman** [comment]
@MBarti actually I believe [this repo](https://github.com/taherkaraki/homebridge-homesung-tv) is the most recent/up-to-date fork of homesung. The repo seems to only support H and J models, not the U ones you and I have (I'm not sure what the difference is between models).

**Comment by MBarti** [comment]
The series is denoted by the 5th sign, I have the J series (ue65J....). Anyway, I hope someone who can code could update homesung.

**Comment by PedroRA561** [comment]
Strange enough the UE50JU6900 does not work (my not this issue but an issue of my own) but the UE32M5525 worked at the first try. 

maybe I am missing something on the UE50JU6900 … any ideas ?

**Comment by MBarti** [comment]
Why would UE50**J**U6900 work? It's the J series, which is exactly what this topic is about.
UE32**M**5525 is the M series, which is much newer.

**Comment by PedroRA561** [comment]
Ok fair enough. I believed the series was the first digit. For now there is still no solution right ? Again not trying to push anything as the plugin is working great with the newer model

**Comment by MBarti** [comment]
No solution. It's probably easy to program, but no-one in this thread seems to have the skills or the will.

**Comment by tavicu** [comment]
Hi! I have created a new milestone for PIN Support! Unfortunately as i told before developing this feature require a lot of time! Especially since i don't have a device that works with this method!

Right now i find the FrameTV more important to be implemented than the PIN method! And even for that it's very hard for me to find some spare time!

I have started developing it for my needs and I released it so other can use it and have the same awesome features like me!
So please, understand that i'm not obligated to have the "will" to invest my spare time to do this instead of spending time with my family!

**Comment by oorakci** [comment]
Hi,

Is there any news about the pin support feature? I've seen the frame tv features has been implemented.

**Comment by tavicu** [comment]
Hi @oorakci,
The pin method will not be implemented.
