### ISSUE TITLE
Slider volume in homekit instead of a switch?

### ISSUE THREAD

**Issue by teymur1988** [tavicu/homebridge-samsung-tizen#154]
Hi tavicu,

Thanks a lot for this amazing thing you wrote! It helps a lot having Samsung TV in home app. Would it be possible to implement volume control as a slider instead of a switch?

Regards

Teymur

**Comment by tavicu** [comment]
Hi,

Unfortunately Homekit doesn't support this. And even if it supports this won't be possible since samsung doesn't have an api where you can get the current volume.

You can also control the volume from the Remote Control. When you are selecting the TV, the volume switches from the phone will actually control the TV volume.

**Comment by teymur1988** [comment]
> Hi,
> 
> Unfortunately Homekit doesn't support this. And even if it supports this won't be possible since samsung doesn't have an api where you can get the current volume.
> 
> You can also control the volume from the Remote Control. When you are selecting the TV, the volume switches from the phone will actually control the TV volume.

Hi,
Homekit does support sliders as brightness for example, I got that working on webos LG tv. But do get your point that in tizen there is no way to get the current volume... Thanks a lot though!
