### ISSUE TITLE
Select specific applications like Netflix

### ISSUE THREAD

**Issue by logictester** [tavicu/homebridge-samsung-tizen#18]
@tavicu opening this to work on implementing a way to select a specific application like Netflix through API commands
Thanks

**Comment by eduardoboucas** [comment]
I'm also interested in this! Let me know if/how I can help.

**Comment by logictester** [comment]
@tavicu any chance you'll have some time to work on this as well? Thank you!

**Comment by tavicu** [comment]
Hei @logictester, i will do it on the next week :)

**Comment by brjborja** [comment]
@tavicu Thank you!

**Comment by tavicu** [comment]
Hei. Just wanted to give you an update of this issue.

Tomorrow i will to the implementation and probably release it the day after tomorrow after some testing.

Also i have just released a new version with some fixes and improvements :)

**Comment by logictester** [comment]
@tavicu THANK YOU!

**Comment by tavicu** [comment]
Good news :)

Just pushed a release with two new features. 

1. Open applications
And yes, you can create automations for this switch because it's not stateless!
You can find here how to create a switch: https://github.com/tavicu/homebridge-samsung-tizen#open-application
And here you can find application ids: https://github.com/tavicu/homebridge-samsung-tizen#applications

2. Refresh switches in real time (YES! YOU CAN CREATE AUTOMATIONS)
This is OFF by default. So you will have to turn it on only if you want to use it.
I must say it does add a very small load because it will check all switchs status every 500ms. But it's very performant, taking only 50ms for every switch.

You can read more here: https://github.com/tavicu/homebridge-samsung-tizen#update-in-real-time-on-the-background

**Comment by logictester** [comment]
Bro - this is amazing!!!! works like a charm!! thank you so much! will continue testing!!!

**Comment by tavicu** [comment]
Let me know if you find a problem and will fixit it asap :)

**Comment by eduardoboucas** [comment]
@tavicu this works wonderfully, thanks! could you share any info on how I can find the ID of an application?

**Comment by tavicu** [comment]
Hei @eduardoboucas , it's not very easy to find the ID. But i will implement a method tomorrow to get all installed applications and write them to the console so you can get the ID from there :)

**Comment by eduardoboucas** [comment]
that's perfect, thank you! as a side note, I just noticed that sending a `KEY_HDMI[x]` command (e.g. `KEY_HDMI3`) won't work for me, somehow. the console says `Command: Command sent with success to TV`, but nothing happens.

should I create a separate issue, or do you have any quick pointers I could try to debug? thanks again!

**Comment by logictester** [comment]
The only HDMI command that ever worked for me was HDMI, sending a specific HDMI never seemed to work

**Comment by tavicu** [comment]
Same here ... never worked!
I will try to look tomorrow for a solution

**Comment by tavicu** [comment]
Hei. Pushed a new release.

Now you can start the homebridge server with this command `homebridge tizen-apps` and will show a table with all your apps and ids.

Make sure the TV is on and paired.

**Comment by eduardoboucas** [comment]
Did you find the reason for the HDMI issue?

**Comment by tavicu** [comment]
> Did you find the reason for the HDMI issue?

Tried now and also checked the TV logs. It looks like the keys are not existing. I will look more tomorrow and see if there is solution.
