### ISSUE TITLE
Siri says that doesn't respond 

### ISSUE THREAD

**Issue by greensouth** [tavicu/homebridge-samsung-tizen#260]
Hi! For the last few weeks Siri says that the device didn't respond (the TV) when triggering scenes, but in fact it's working flawlessly. Don't know why but it's quite annoying.

Any clue?

**Comment by Dean151** [comment]
Have the same here, but I just need to ask Siri to turn the tv ON to reproduce.

**Comment by greensouth** [comment]
> Have the same here, but I just need to ask Siri to turn the tv ON to reproduce.

That happens also, when turning the tv on, or off

**Comment by apexad** [comment]
Possibly related to #267

**Comment by tavicu** [comment]
No problem here. It's working ok on my side. What do you have in the logs?

**Comment by radiocolin** [comment]
I'm seeing the same. Sometimes shows as "no response" in Home.app, and Siri tells me it's not responding as it's turning the TV on.

Log says "[08/01/2021, 17:17:35] [Living Room TV] Failed to power on the TV" but the TV turns on.

**Comment by Dean151** [comment]
Seems like we're having a timeout at powering-on via WoL.
Maybe we could add a parameter for setting up a greater timeout since default is 5s? Or is there a Siri timeout I'm not aware of?
On my network, I've a lot of weird custom rules ; especially on firewall ; but since I'm far from being the only impacted here, we can assert that it's not the only root cause.
My TV is from 2016, and is wired. Maybe it's simply too slow.

```
[18/01/2021, 17:43:28] [Télévision] Failed to power on the TV
[18/01/2021, 17:43:28] [Télévision] [DEBUG] WoLFailedError: Failed to power on the TV
    at /usr/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:228:20
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by tavicu** [comment]
Hei. I was able to find something.
First, the 5s timeout is for other thing, not WoL timeout. It's to stop you from toggling on/off for 5 seconds :)

WoL doesn't have a timeout but i found that sometimes when i ask siri to do something (turn on the lights) it responds veeeery slow (10+ seconds). i think this is related to your problems.

Unfortunately there is nothing i can do since there is no timeout for WoL. It just waits it's answer then say success or failed.

I think the problem is from Siri since i never had problems when used Alexa to change the state of TV.

We may find some improvements with the newer homebridge version (1.3.0) which optimised a lot of things.

If you encounter this problem again let me know

**Comment by Dean151** [comment]
I updated yesterday homebridge and the pluging. It seems to 🚀 
Thanks!!!
