### ISSUE TITLE
Adding additional apps with codes

### ISSUE THREAD

**Issue by fklement** [tavicu/homebridge-samsung-tizen#261]
I've some additional codes that would be nice to extend in the wiki.

| Application             | ID                 |
| :---------------------- | :----------------- |
| YouTube                 | 111299001912       |
| Netflix                 | 11101200001        |
| HBO GO                  | 3201706012478      |
| Internet                | org.tizen.browser  |
| Steam Link              | 3201702011851      |
| Prime Video             | 3201512006785      |
| All 4                  | 111299002148       |
| Apple TV               | 3201807016597      |
| BBC News               | 3201602007865      |
| BBC Sport              | 3201602007866      |
| BBC iPlayer            | 3201601007670      |
| BT Sport               | 3201811017267      |
| CHILI                  | 3201505002690      |
| Disney+                | 3201901017640      |
| Facebook Watch         | 11091000000        |
| Gallery                | 3201710015037      |
| Google Play Movies     | 3201601007250      |
| ITV Hub                | 121299000089       |
| McAfee Security for TV | 3201612011418      |
| My5                    | 121299000612       |
| NOW TV                 | 3201603008746      |
| Rakuten TV             | 3201511006428      |
| Samagic                | vWMh8q6Ce0.Samagic |
| SmartThings            | 3201710015016      |
| Spotify                | 3201606009684      |
| Universal Guide        | 3201710015067      |
| hayu                   | 3201806016381      |

**Comment by tavicu** [comment]
Thank you! I will update the wiki!

**Comment by benjamin2209** [comment]
Hello can you explain the method to list all the apps on the TV please ? I search the code of the MOLOTOV app

**Comment by DrJapan** [comment]
Hello!

Here is an updated list of applications and their respective codes:

1 - Netflix]
- App Name                            :     Netflix
- App Version                         :     5.2.550
- App ID - WAS                        :     3201907018807
- App ID - Tizen                      :     org.tizen.netflixapp
-----------------------------------------------------------------------------------------------------
[ 2 - Prime Video]
- App Name                            :     Prime Video
- App Version                         :     2.01.23
- App ID - WAS                        :     3201910019365
- App ID - Tizen                      :     org.tizen.primevideo
-----------------------------------------------------------------------------------------------------
[ 3 - Apple TV]
- App Name                            :     Apple TV
- App Version                         :     6.1.0
- App ID - WAS                        :     3201807016597
- App ID - Tizen                      :     com.samsung.tv.ariavideo
-----------------------------------------------------------------------------------------------------
[ 4 - YouTube]
- App Name                            :     YouTube
- App Version                         :     2.1.498
- App ID - WAS                        :     111299001912
- App ID - Tizen                      :     9Ur5IzDKqV.TizenYouTube
-----------------------------------------------------------------------------------------------------
[ 5 - Gallery]
- App Name                            :     Gallery
- App Version                         :     1.9.216
- App ID - WAS                        :     3201710015037
- App ID - Tizen                      :     com.samsung.tv.gallery
-----------------------------------------------------------------------------------------------------
[ 6 - Internet]
- App Name                            :     Internet
- App Version                         :     3.1.11260
- App ID - WAS                        :     3201907018784
- App ID - Tizen                      :     org.tizen.browser
-----------------------------------------------------------------------------------------------------
[ 7 - Apple Music]
- App Name                            :     Apple Music
- App Version                         :     2.1.0
- App ID - WAS                        :     3201908019041
- App ID - Tizen                      :     org.tizen.apple.applemusic
-----------------------------------------------------------------------------------------------------
[ 8 - Facebook Watch]
- App Name                            :     Facebook Watch
- App Version                         :     2.0.34
- App ID - WAS                        :     11091000000
- App ID - Tizen                      :     4ovn894vo9.Facebook
-----------------------------------------------------------------------------------------------------
[ 9 - eManual]
- App Name                            :     eManual
- App Version                         :     2.1.4
- App ID - WAS                        :     20202100004
- App ID - Tizen                      :     OzNoIbpz56.emanual
-----------------------------------------------------------------------------------------------------
[ 10 - Tubi  Free Movies ＆ TV]
- App Name                            :     Tubi  Free Movies ＆ TV
- App Version                         :     2.0.26
- App ID - WAS                        :     3201504001965
- App ID - Tizen                      :     3KA0pm7a7V.TubiTV
-----------------------------------------------------------------------------------------------------
[ 11 - Spotify  Music and Podcasts]
- App Name                            :     Spotify  Music and Podcasts
- App Version                         :     1.7.2
- App ID - WAS                        :     3201606009684
- App ID - Tizen                      :     rJeHak5zRg.Spotify
-----------------------------------------------------------------------------------------------------
[ 12 - CTV]
- App Name                            :     CTV
- App Version                         :     7.0.9
- App ID - WAS                        :     3201506003486
- App ID - Tizen                      :     0hmTUj2VQe.CTVGO
-----------------------------------------------------------------------------------------------------
[ 13 - Crave]
- App Name                            :     Crave
- App Version                         :     150.0.203
- App ID - WAS                        :     3201506003488
- App ID - Tizen                      :     SKvHIMBcln.CraveTV
-----------------------------------------------------------------------------------------------------

Even with the new codes, I've realized the issue is with the java code. The code relies on http://(ip of tv):8001/api/v2/applications to populate the list of applications, but when going to that url, all that comes up is: <html><body>404</body></html>, so then the plugin throws an error and the supplied ID isn't verified against the non-existent list. 

If there is some way to get the plugin to act like a remote device manager, then there would be a way for the device manager to query the TV for the list of applications. Hence how I was able to get this list.

**Comment by tavicu** [comment]
Hei! Thank you for the support. I didn't update the wiki yet because those IDs changed on the newer TV.

So i have to make sure the wiki could be understand by everybody and also help people with newer and older TVs

**Comment by tavicu** [comment]
Hi, I have updated the wiki: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications

**Comment by offtohavasu** [comment]
If anyone can help getting the DirecTV Stream code that would be very helpful. I tried using the Tizen Studio, but I'm restricted on my laptop from installing it.

Thanks in advance!
