### ISSUE TITLE
No ON or no OFF

### ISSUE THREAD

**Issue by loop2** [tavicu/homebridge-samsung-tizen#277]
HI!,
I have 3 TVs samsung an old 5 series a Q85R and a 7 series...
All cable connected and fully working for shutoff with Alexa... no switch on...

With home kit, I can switch on the 5 series TV but no switch off...
The Q85R and 7 series switch off but no switch on...

In the plugin configuration there are many options... any idea?
thanks a lot

**Comment by razvanra2** [comment]
Hi, I was about to add a +1 to this issue a couple of hours ago after not understanding why all of a sudden my living room tv would not power on, but accept all other commands, especially since it was working fine for literally months.
Figured out that in my case the issue was with the tv, not the plug in.
Try my fix, see if it works for you too:
- remove tv from list in hoobs
- restart hoobs
- on your tv, go into settings ->general-> external device manager ->device connection manager -> device list, select them all, then delete
- re-add device to hoobs. make sure to click "accept" (or "approve") on the pop-up bar on your tv when it prompts you

**Comment by tavicu** [comment]
Closed the issue since we didn't get any debug logs and we are not wizards :)
Please read the Wiki
