### ISSUE TITLE
App Identification

### ISSUE THREAD

**Issue by Doubledeucedavis** [tavicu/homebridge-samsung-tizen#291]
When I create a switch or a custom input, I get the error that the app ID doesn't exist. I was attempting to use Netflix: 11101200001

**Comment by DrJapan** [comment]
It appears that with the new models of TVs this year, Samsung has decided to change the way applications are called over LAN. It seems that the application IDs are no longer valid. I have a feeling like the application IDs have transitioned over to a org.tizen.netflix type of sequence.

So, without getting root access to the new TVs or a way to decrypt the .mds updates, we won't be able to get the application ids for Spotify, or Apple TV+, or the applications not on the remote.

I've been doing some reading and tinkering with inputs/switches/commands, and here's what I'm thinking:
The newer Samsung TVs come with remotes that have physical Netflix and Amazon Prime buttons. As we're able to program switches that allow us to change source, or mute, there must be a KEY_COMMAND that triggers the corresponding application.

KEY_MUTE works and so does KEY_SOURCE with newer TVs, so I'm thinking there must be a way to get a button for Netflix or Prime Video (Whatever physical buttons people have).
If anyone knows how to get the list of available remote commands from the TV, that would be epic, or if you have anything to add, please chime in.

**Comment by tavicu** [comment]
@DrJapan Even if there is a KEY ... all the "inputs" functionality will be gone since we can't check for status ...
In my country i'm on the latest OS and everything works. Probably the new OS was released only in some countries

**Comment by Doubledeucedavis** [comment]
That makes more sense. It is a brand new Samsung TV I got 2 months ago. I live in the US and I will try to figure it out. If I do I’ll let you know

**Comment by DrJapan** [comment]
Hello!

Here is an updated list of applications and their respective codes:

1 - Netflix]

App Name : Netflix
App Version : 5.2.550
App ID - WAS : 3201907018807
App ID - Tizen : org.tizen.netflixapp
[ 2 - Prime Video]

App Name : Prime Video
App Version : 2.01.23
App ID - WAS : 3201910019365
App ID - Tizen : org.tizen.primevideo
[ 3 - Apple TV]

App Name : Apple TV
App Version : 6.1.0
App ID - WAS : 3201807016597
App ID - Tizen : com.samsung.tv.ariavideo
[ 4 - YouTube]

App Name : YouTube
App Version : 2.1.498
App ID - WAS : 111299001912
App ID - Tizen : 9Ur5IzDKqV.TizenYouTube
[ 5 - Gallery]

App Name : Gallery
App Version : 1.9.216
App ID - WAS : 3201710015037
App ID - Tizen : com.samsung.tv.gallery
[ 6 - Internet]

App Name : Internet
App Version : 3.1.11260
App ID - WAS : 3201907018784
App ID - Tizen : org.tizen.browser
[ 7 - Apple Music]

App Name : Apple Music
App Version : 2.1.0
App ID - WAS : 3201908019041
App ID - Tizen : org.tizen.apple.applemusic
[ 8 - Facebook Watch]

App Name : Facebook Watch
App Version : 2.0.34
App ID - WAS : 11091000000
App ID - Tizen : 4ovn894vo9.Facebook
[ 9 - eManual]

App Name : eManual
App Version : 2.1.4
App ID - WAS : 20202100004
App ID - Tizen : OzNoIbpz56.emanual
[ 10 - Tubi Free Movies ＆ TV]

App Name : Tubi Free Movies ＆ TV
App Version : 2.0.26
App ID - WAS : 3201504001965
App ID - Tizen : 3KA0pm7a7V.TubiTV
[ 11 - Spotify Music and Podcasts]

App Name : Spotify Music and Podcasts
App Version : 1.7.2
App ID - WAS : 3201606009684
App ID - Tizen : rJeHak5zRg.Spotify
[ 12 - CTV]

App Name : CTV
App Version : 7.0.9
App ID - WAS : 3201506003486
App ID - Tizen : 0hmTUj2VQe.CTVGO
[ 13 - Crave]

App Name : Crave
App Version : 150.0.203
App ID - WAS : 3201506003488
App ID - Tizen : SKvHIMBcln.CraveTV
Even with the new codes, I've realized the issue is with the java code. The code relies on http://(ip of tv):8001/api/v2/applications to populate the list of applications, but when going to that url, all that comes up is: 404, so then the plugin throws an error that the supplied ID can't verified against the non-existent list.

If there is some way to get the plugin to act like a remote device manager, then there would be a way for the device manager to query the TV for the list of applications. Hence how I was able to get this list.

**Comment by tavicu** [comment]
Hei. Please follow this issue #264

I've made an update for the plugin to use new method of opening the apps which should be compatible with newer TVs too.

Regarding the ID of the app, looks like it differs from region to region and based on your TV model. On some newer TVs the new Netflix id is `3201907018807`. So you can try this settings too.

**Comment by DrJapan** [comment]
@tavicu Let me know if you need any help setting up said Wiki.
