### ISSUE TITLE
Home App TV shows ON when TV is actually off and vice versa

### ISSUE THREAD

**Issue by todesto** [tavicu/homebridge-samsung-tizen#300]
Doesn't happen all the time, but it happens enough to get annoyed.
Home app shows on, TV is off, then I have press two three times, then it will work.

Any suggestion?

**Comment by xnonim** [comment]
same problem

**Comment by tavicu** [comment]
A restart of homebridge can fix it.
There are many scenarios that can fail and from your "description" i did not understand the exact scenario.

For example if you turn the TV off from remote it will still be ON in a sleeping state for ~15 seconds. So the homebridge will still see the TV on even if it's "off"

All the checks for tv status are hacks because we don't have an api from samsung.
So there is a margin error. Nothing we can do
