### ISSUE TITLE
Turning On after some time

### ISSUE THREAD

**Issue by benov84** [tavicu/homebridge-samsung-tizen#320]
Hi,
My TV is working great (Series 4).
The only problem is that the TV is turning on only if it is turned off right before that. After a period of time it doesn't turning on.
I have a Samsung TV remote app (https://apps.apple.com/bg/app/remote-tv-control-for-samsung/id983088149) on my iPhone that can turn the tv on, so the problem is not in my TV.
Any ideas?

**Comment by tavicu** [comment]
After you turn off the TV it will stay in a standby state for around 15 seconds.

The plugin checks if it's in the standby and if it is then just sends the power command to TV.
If you try to turn the TV on after the 15 seconds passed the plugin sees the TV as offline and sends a Wake on Lan command to turn the TV off. The WoL command is sent to the mac address you set in your config.

So:
1. Make sure you have the correct mac address in config. If TV is connected via WiFi get the WiFi mac, if it's by Wire, get the wire mac.
2. Make sure your network allows WoL requests and that they are not blocked by your router.
3. And the last one, one of my TVs don't support WoL over WiFi so i had to connect it with ethernet wire in order to make it work! Maybe it's your case

**Comment by benov84** [comment]
Hi, thank you very much!
Unfortunately, I can't get this to work.
1. My TV is wire connected and the Mac is right.
2. As I wrote I have an app on my iPhone that can power on the TV when it is offline, so the TV suppers wake on lan and the router is not blocking it.
Maybe something on the homebridge server PC?

**Comment by tavicu** [comment]
Yup, homebridge can also be a problem depending on how you installed it and what ports are blocked.

Unfortunately this is something that i can't help you debugging it since it's a problem on your Homebridge setup or on the Network.

**Comment by benov84** [comment]
Thank you very much! I will check the server config.
Thank you for your support and for the great plug-in!

**Comment by tavicu** [comment]
Hei @benov84, Just found a thing on my TV, don't know if it applies to you but see if you have the option.

In Settings > General > Network > Expert settings > Power on with mobile (turn on) and **enable IP remote**.

**Comment by benov84** [comment]
Hi, thank you, but this option was already activated and this is not the problem. I will try to investigate, and if I succeeded I will write you just to know what was the problem :)

**Comment by benov84** [comment]
I've found it, was the MAC address - I have copied it from my router settings. Now I write it (not copied) and it works. Very stupid thing, maybe when I copy it there is some wrong symbol or something. I'm sorry that I waste tour time!
I run wakeyourlan from your code and it returned wrong MAC address, that way I found the problem!
Thanks again! :)

**Comment by tavicu** [comment]
Awesome! I'm glad you found it :)
