### ISSUE TITLE
Samsung QLED (2020) apps switching not working

### ISSUE THREAD

**Issue by ekke1** [tavicu/homebridge-samsung-tizen#322]
I've the problem that I can only switch on/off and mute the TV .
What is not working are any other switches e.g. start an app (e.g. Netflix).
I've tried to use both "switches" and "input"; it's showing up in the home app differently, but won't work.
When using Input all TV apps are showing as "ON" - that seems weird; using switches they appear as off.
In either case nothing is happening if selected.
I've got the values from the TV using the Tizen-Studio on my Mac, so they should be o.k.

Is there any way I can debug what is going on?
Config below; aHomebridge is updated v1.3.3; node v14.16.0 - so all pretty actual.

{
    "devices": [
        {
            "name": "Wohnzimmer TV",
            "ip": "192.168.2.120",
            "mac": "4C:C9:5E:DE:46:8C",
            "switches": [
                {
                    "name": "Sky",
                    "type": "app",
                    "value": "3201411000562"
                },
                {
                    "name": "AppleTV",
                    "type": "app",
                    "value": "3201807016597"
                },
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "3201907018807"
                },
                {
                    "name": "Mute",
                    "mute": true
                }
            ]
        }
    ],
    "platform": "SamsungTizen"
}

**Comment by tavicu** [comment]
Hi. Are you using the latest version of the plugin? This was fixed 4.3.7

Now the plugin uses a new method to open applications.

You can try in your Terminal to run this command `curl -X POST -i http://<YOUR_IP>:8001/api/v2/applications/3201907018807` (replace <YOUR IP>) and tell me what happens. Also make sure your TV is ON when you run this command.

**Comment by ekke1** [comment]
Hi
- in the ui-x it is displayed as: homebridge-samsung-tizen v4.4.1
- now confusingly: the curl commands are WORKING fine (used the RaspPi, where HB  is running on).

**Comment by tavicu** [comment]
Can you show me your config?

**Comment by ekke1** [comment]
1) what I forgot and it might give a hint: I’m NOT seeing a remote control in the home app.
2) here is what I get from the TV as version : "uri":"http://,IP>:8001/api/v2/","version":"2.0.25"
3) config:

{
    "devices": [
        {
            "name": "Wohnzimmer TV",
            "ip": “192.168.xxx.xxx",
            "mac": "4C:C9:5E:DE:46:8C",
            "inputs": [
                {
                    "type": “app",
                    "name": "Sky",
                    "value": "3201411000562"
                },
                {
                    "type": "app",
                    "name": "AppleTV",
                    "value": "3201807016597"
                }
            ],
            "switches": [
                {
                    "name": "Mute",
                    "mute": true
                }
            ]
        }
    ],
    "platform": "SamsungTizen"
}

**Comment by tavicu** [comment]
1) You will never see it :) cause it's not in home app, it's in control center. https://github.com/tavicu/homebridge-samsung-tizen/issues/305#issuecomment-778611523
2) Yup, since the curl command worked, your TV is compatible
3) Config looks fine. How are you trying to switch inputs? Cause to take action you need to slide to the app you want to open. By default Sky Input will be as first option and it appears as selected, but it's not! If you want to switch to Sky you have to slide the box down and back again on the Sky input.
That's why i recommend adding another first option as Live TV. Example:
```
"inputs": [
    {
        "name": "Live TV",
        "type": "command",
        "value": "KEY_SOURCE,KEY_DOWN,KEY_UP,KEY_LEFT*3,KEY_ENTER"
    },
    {
        "name": "Netflix",
        "type": "app",
        "value": "11101200001"
    }
]
```

**Comment by ekke1** [comment]
1) found it in the Control Center - works there.
2) But Not still any “Inputs” only the mute command is working

**Comment by tavicu** [comment]
Try to add a switch like this:
```
"switches": [
    {"name": "Netflix", "app": "3201907018807"}
]
```

and then open the homebridge in debug mode with `homebridge -D`

Let me know what you get in console when you press the switch.

**Comment by ekke1** [comment]
This is what completely works now:
(BTW: KEY_UP*2 should not have been needed, since it’s only to be pressed once, but after some trial and error, I got it to work like that)

THX!!!!!!!



 "switches": [
                {
                    "name": "LiveBox",
                    "command": "KEY_RETURN,KEY_UP*2,KEY_ENTER"
                },
                {
                    "name": "Netflix",
                    "app": "3201907018807"
                },
                {
                    "name": "AppleTV",
                    "app": "3201807016597"
                },
                {
                    "name": "Sky",
                    "app": "3201411000562"
                },
                {
                    "name": "Mute",
                    "mute": true
                }

**Comment by tavicu** [comment]
Now try to set them as inputs :)

it’s the same code! So if switches worked, inputs should also work!

You just have to figure out how they work in home app :)

![A820BE6D-33CC-41B5-9131-8A59E04F3713](https://user-images.githubusercontent.com/172068/111469030-e418ad80-872e-11eb-9f93-a5a16d83ef04.jpeg)

**Comment by ekke1** [comment]
If I’m using inputs, nothing shows up below the big blue power button, the slider ox is simply not there, but that I can live with….

**Comment by Joshua1264** [comment]
Hi,
I‘m also using a QLED 2020. I have managed to get all apps working by using switches.
However I cannot figure out how to select LIVE TV. I have tried multiple key entries as input, found on this Wiki, but none succeeded. I have a key on both of my different remotes which is the ‚HOME‘ key, but it seems I cannot map it.
Do you have any ideas?
Thank you

**Comment by ekke1** [comment]
Have you tried “KEY_SOURCE” ?- works for me

**Comment by tavicu** [comment]
> If I’m using inputs, nothing shows up below the big blue power button, the slider ox is simply not there, but that I can live with….

It's ok. Because you set the inputs after setting the TV they will appear as separate accessories. Just give it a time and also a force close to Home app! They should be there :) https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--inputs-are-appearing-like-separate-accessories


> That does not work!
> Going crazy, was able to integrate all apps, but no possibility to go back to Live TV!

This is how i have it set up: `{"name": "Live TV", "type": "command", "value": "KEY_SOURCE,KEY_DOWN,KEY_UP,KEY_LEFT*3,KEY_ENTER"}`

**Comment by ekke1** [comment]
try this:

"switches": [
                {
                    "name": “Live TV",
                    "command": "KEY_SOURCE,KEY_LEFT*5,KEY_RIGHT,KEY_UP*2,KEY_ENTER"
                },

**Comment by Joshua1264** [comment]
This is how i have it set up: {"name": "Live TV", "type": "command", "value": "KEY_SOURCE,KEY_DOWN,KEY_UP,KEY_LEFT*3,KEY_ENTER"}

I will try this as Input, but this seems too many commands to me, because on my remote to switch, let's say from Netflix to Live TV, I push the HOME button on the remote, then 1 right click (being then on Live TV icon) and ENTER, that's all.
Do we speak here about a Samsung QLED with Smarthub?

**Comment by tavicu** [comment]
You should find the combination that works best for you. Maybe from Netflix to Live TV you have on key to the left indeed, but what if you have one more app, let's say youtube and it's the 3rd. Now you have two keys to the left so the command you where thinking about it's not working anymore because you will need only one when you are on netflix and two when you are on youtube. WIth `KEY_SOURCE` you can't go wrong :)

I have more TVs and that command applies to all of them :)

**Comment by Joshua1264** [comment]
Working now :-)
Used the command from ekke1...thank you so much!

**Comment by ekke1** [comment]
- it might be different depending on the individual set-up.
For me I have to select my DB920 from the input menu in the smart hub, since I’m not using the build-in tuner of the TV.
Then sometimes being a “SMART”-hub it feels to show some things to propose and advertise - once in a while.
So my solution is to go all the way to the left (after KEY_SOURCE) and then start from there as basis…
From there, one the the right is ALWAYS bringing you to the TV-Inputs.
Took me a while to figure how to outsmart Smart Hub ;)

**Comment by Joshua1264** [comment]
Good solution ekke1!
Anyway it's just working fine now for me.
Thanks again!!

**Comment by martinschki** [comment]
Sorry for opening this up again:
Is the app id up there for the Sky app or the sky X app??
I need the app id for sky x and can't find it anywhere...
