### ISSUE TITLE
Doesn´t turn on after long time off

### ISSUE THREAD

**Issue by Nathansm32** [tavicu/homebridge-samsung-tizen#336]
I have been using this plug in for a while now, but everytime my tv is off for a while, i must turn it on with the remote, is there any way to fix this?

**Comment by tavicu** [comment]
Hi. Your TV don't turn on after some time because it goes into sleep and the only way to wake it up is by wake on lan, which the plugin uses.

On some TV you must allow this method from the settings (as jackklink said)
> You might need to enable “Power On with mobile” in Network settings on the TV.
> Settings>General>Network>Expert Settings

Other TVs don't support Wake on Lan on WiFi and needs to be connected with cable (one of my TVs is like this, i tried even resetting it, but nothing ...)

Other possibility is that you insert a wrong mac address in config :D
