### ISSUE TITLE
FrameTV switches present not neat

### ISSUE THREAD

**Issue by mmarras** [tavicu/homebridge-samsung-tizen#347]
Not trying to be overly critical, and also not sure if we can do anything about it on the plugin-level, but the Frames switches are presented kind of not neat because the on-off switch is just a button and is two column with the art-mode switch. The rest that follows is one column again. Can we have everything in one column? Of course we can just remove some switches from the display altogether, just curious if that could be improved. 
**Mac.Home.app**
<img width="901" alt="Screenshot 2021-04-17 at 11 14 18" src="https://user-images.githubusercontent.com/53915566/115108101-ec9f1680-9f6e-11eb-9f76-7ad6ca70327f.png">
**iPhone.home.app**
![IMG_9234B07ED348-1](https://user-images.githubusercontent.com/53915566/115108149-21ab6900-9f6f-11eb-8920-f04bb0b865a4.png)

**Mockup of arguably more desired layout**
![Mockup](https://user-images.githubusercontent.com/53915566/115108395-874c2500-9f70-11eb-9504-10181d8ab087.png)

**Comment by tavicu** [comment]
Apple decides how to display the switches, not us!

For disabling them: https://git.io/JOII1

**Comment by mmarras** [comment]
Well nothing we can do here is again a bit of a rushed conclusion, imho. 
Maybe if we think a moment we can still come up with an improvement? If we cannot change the alignment, there might be other ways to improve. For example wouldn’t it look nicer, i.e., more symmetric, if the TV switch (round) would be below the two slider switches? Another question comes to mind: why are the additional ones sliders in the first place and round as the on-off buttons too? I have seen groups with only sliders, so clearly all three could be sliders, that would already be an improvement in my opinion.

**Comment by tavicu** [comment]
Because that's how TVs are shown, with a rounded button.
It's not rushed, i know how this work since this plugin was made almost 4 years ago ... so i had a long time learning how homekit works and what options do we have.

If you want more informations you could write to Apple :) I would like the option to customise as much as you want 

As i already told you (and not rushed, but from days spent trying to find an option), on our side there is nothing we can do.
TVs has rounded button as power and additional switches are shown like that. As a device you cannot decide how to display your stuff. You only get the option to set them.

**Comment by mmarras** [comment]
Thanks for the satisfactory additional explanation.

**Comment by tavicu** [comment]
And i'm sorry for my tone but i don't like things like "rushed conclusion", "so clearly all three could be sliders", and others.
If you think you can do better, feel free to do it.

But i spent months on this plugin to get it to this stage and i really know how things work! I don't appreciate when someone comes to crash my party :)

Trust me when i tell you i also don't like how Apple display them. Personally i keep them as separate tiles!
