### ISSUE TITLE
Idea for new feature

### ISSUE THREAD

**Issue by marithpl** [tavicu/homebridge-samsung-tizen#35]
Thanks a lot for running apps & refresh it's a huge help!
I think it's the best plugin to my homebridge devices because of functionality and your involvement!

I try to modify my actual scenes & automation. What may be helpful?
Adding a delay parameter to delay actions (clicks on TV).

For example              
{"name" : "SPOTIFY",
"power" : true, // Check if power is on
"app" : "3201606009684", // Run Spotify App
"delay" : 2000 // 2000ms
"command" : "KEY_ENTER*2" // Click on first playlist and play music
}

Do you think is possible?
Now I'm turning radio channel every morning but what can be better than favorite songs in this winter mornings :)

**Comment by tavicu** [comment]
Hei! There is already an option for delay :)

Please see the readme on Device settings section :)

**Comment by tavicu** [comment]
:) that’s an easy implementation! I will add it this week and push a new release.

Kepp you posted

**Comment by marithpl** [comment]
I reported also problem with asking for permission when homebridge is restarted.
In TV i have disabled this option

**Comment by marithpl** [comment]
I know and I have

**Comment by Rens93** [comment]
> :) that’s an easy implementation! I will add it this week and push a new release.
> 
> Keep you posted

Is this done ?

**Comment by tavicu** [comment]
Hey, sorry for the late response. Since with the holidays my time was limited.

I will have a look this weekend.

**Comment by marithpl** [comment]
Hi tavicu how your works? :)

**Comment by tavicu** [comment]
Hi,

I know it was a long time since you opened this issue and promise i will resolve it.

i already did it in the new version that will be released once iOS 12.2 will be release.
Until then if you want i can help you changing the source files to work.
Let me know if you want.

**Comment by marithpl** [comment]
Sure I wish.

**Comment by tavicu** [comment]
Hi, here you can see the changes that need to be done: https://github.com/tavicu/homebridge-samsung-tizen/pull/64/files

You will be able to add the `wait` parameter to switch in seconds.

It will run before `command` option and unfortunately as it is right now you will not be able to add multiple waits because the value of the switch is an object where the key is unique. 

So even if you add it more times in the list, it will only take the last declared value.

Keep in mind that it's not tested.
Let me know :)
