### ISSUE TITLE
Homekit status refresh problem 

### ISSUE THREAD

**Issue by neotic82** [tavicu/homebridge-samsung-tizen#368]
I wanted to ask how the issue #141 has been since I am finding the same problem, with the TV on, the homekit appears to me on and after a few seconds it seems that it is off.

Thank you for your great job @tavicu :)

**Comment by tavicu** [comment]
Hi!

The problem was resolved but only for TVs that support the PowerState feature.

You can check by accessing `http://TV_IP:8001/api/v2/` and see if you have a PowerState key in response:
![Screenshot 2021-05-31 at 11 39 03](https://user-images.githubusercontent.com/172068/120165995-d12d5980-c204-11eb-98b8-cb5f351003b3.png)
