### ISSUE TITLE
Add delay after Turn On TV Help

### ISSUE THREAD

**Issue by asyba** [tavicu/homebridge-samsung-tizen#369]
How I can make that after turning ON the TV wait some seconds and open the App Netflix?

I'm traying with HomeKit a Scene but it executes at the same time (TurnOn TV and switch(Netflix) ) and it doesn't work.

**Comment by tavicu** [comment]
Are you using switches?

**Comment by webjib** [comment]
Same for me. I’m using a switch to power on the TV and go to a specific channel (let’s say channel 27). I’ve added « power: true ». But sometimes only the last number is sent (7 but not 2). A small delay after switch on will probably help.

**Comment by asyba** [comment]
> Are you using switches?

yes, I manage to do it with iOS Shurtcutts.
1 dummy switch with other plugin and with that run iOS Shortcut:
TV on, wait 5seconds, then Open App Netflix

**Comment by tavicu** [comment]
> Same for me. I’m using a switch to power on the TV and go to a specific channel (let’s say channel 27). I’ve added « power: true ». But sometimes only the last number is sent (7 but not 2). A small delay after switch on will probably help.

There is a delay for 1.5 seconds after the TV starts. What you could do is using commands:
`{"name": "Command 1", "power": true, "command": "DELAY*2s,KEY_2,KEY_7,KEY_ENTER"}`


> yes, I manage to do it with iOS Shurtcutts.
> 1 dummy switch with other plugin and with that run iOS Shortcut:
> TV on, wait 5seconds, then Open App Netflix

I will check to see if increasing the delay after the TV is on will help. Or add an option to customize that delay

**Comment by webjib** [comment]
I've tried to create a "Command" switch instead of a "Channel" switch, but for some reason, my TV becomes unstable. Maybe because of repeating an unknown command? And this sort of switch seems less smart, as the delay will be applied all the time, even if the TV is already on.

Adding an option to customise the 1.5 second delay would be awesome, because one would not need to use "command", but only "channel" switch.

Thanks!
