### ISSUE TITLE
Status Refresh causes automation to trigger

### ISSUE THREAD

**Issue by PowerStrike** [tavicu/homebridge-samsung-tizen#371]
I saw that in #126 someone said exactly what I’m facing, but the issue was closed without answer, is there anything to do ?

**Comment by tavicu** [comment]
Hi. The refresh status only ask HomeKit to check the accessory if the status changed.

If the status did not changed it should not toggle any button.

Unfortunately all this is done by Apple and we can't control it!
Also HomeKit is sometimes buggy and not 100% reliable. Maybe with iOS 15 that will change.

But at the moment i can only suggest to hard reset everything related to your smart devices. Maybe it will fix it.
On my end, i tested it and nothing change when the status is refreshed if the state of TV didn't change.

I also have problems with my HomeKit when it comes to automations and that's why i'm not rely on it.
