### ISSUE TITLE
Way to disable from Apple Remote app

### ISSUE THREAD

**Issue by justinshuls** [tavicu/homebridge-samsung-tizen#373]
Currently have a frame tv and an apple tv so when using this plugin i see the tv twice in apples built in remote app / control center remote. Does not appear to be a way to disable.

**Comment by tavicu** [comment]
Hi.

You are the first one to ask this. The TV should appear only in control center, not remote app since the app only load compatible devices).

Also they are not the same. One controls the Apple TV and one the TV itself.

I will take in consideration your suggestion but since you are the only one to ask in a few years at the moment I don't think it's something that needs to be implemented.
