### ISSUE TITLE
Samsung Frame has correct IP and MAC address but no longer works!

### ISSUE THREAD

**Issue by Schachjj** [tavicu/homebridge-samsung-tizen#374]
My Samsung frame no longer appears in my Home app after the update a few months ago that added the additional options for the frame TV. Any thoughts on configurations that I may have messed up?

**Comment by danielero** [comment]
same here

**Comment by tavicu** [comment]
Hi. None of the plugin implementation changed the base settings or something regarding to pairing. So this could be related to something else.
Someone else with this problem was using Hoobs. Could be related to that.
I am using Homebridge and i always make sure to have the latest version and i didn't have any problem :)

You can add the uuid key to your config file so you will force a new uuid for the TV. https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--cant-add-tv-after-removing-or-making-changes
After that you should be able to add it in Home App

**Comment by xundre** [comment]
I also have a Samsung frame , I am able to turn it on , but I cannot turn if off. It never works . Given the frame is really annoying with being powered on all the time , this is what I really need the off button for.

**Comment by tavicu** [comment]
> I also have a Samsung frame , I am able to turn it on , but I cannot turn if off. It never works . Given the frame is really annoying with being powered on all the time , this is what I really need the off button for.

https://github.com/tavicu/homebridge-samsung-tizen/issues/354#issuecomment-827570385
