### ISSUE TITLE
Feature Request: Volume Control optionally as a separate control

### ISSUE THREAD

**Issue by TiPunch69** [tavicu/homebridge-samsung-tizen#379]
I have seen some other plugins that do that and I find it quite usefull. It would be nice to have the volume control as a separate service/control instead of the "standard" way.
Homebridge UI shows it separate and I find it quite comfortable.

**Comment by tavicu** [comment]
This was discussed before and can't be done since we can't take the current volume of TV, so we don't know how to populate the slider. And also you cannot set a specific volume, you can only push up or down. Maybe other TVs have different api and allow this.

I do have an ideea on how to make something but don't know if the time it's worth it since i consider those actions only gimmicks. Why? Because you will need your remote to do more.  For example using inputs and open Netflix? Ok, still need remote to select a movie ...

My ideea was to have a slider that stay at half by default and if you pull it up to increase the volume until you release the slider, and if you pull it down to decrease the volume until you release it :)

But again ... i have more important features that actually make sense to implement.
