### ISSUE TITLE
TV permission

### ISSUE THREAD

**Issue by jakubhavel** [tavicu/homebridge-samsung-tizen#404]
Hi,
I have Samsung QE55Q80T and I successfuly configured the plugin – TV is controlable via Home app on iPhone. 
**However**, every time the bridge or TV is restarted the TV needs the permission to be accepted again. I checked the TV settings and I have these notifications turned off as configuration tutorial says. So TV config should not be an issue. I also noticed that time to time the TV name changes in my Home app – in the plug-in configuration the TV has a different name and I changed it in my Home app. It changes from “TV” to “TV 0CC1”, “TV AB4A” and similar. I suppose this name change happens also after the restart of the bridge.

Here’s the setup I have:
- HOOBS on Raspberry Pi 2 (version: 4.0.100, node version: 14.17.6, homebridge version: 1.3.4)
- plugin version: 5.0.1 (checked for updates a few minutes ago)

And my plugin config:
`{
    "platform": "SamsungTizen",
    "app_list": true,
    "devices": [
        {
            "name": "TV",
            "ip": "192.168.0.118",
            "mac": "98:06:3C:05:8B:BD",
            "uuid": "A1",
            "inputs": [
                {
                    "name": "HBO GO",
                    "type": "app",
                    "value": "3201706012478"
                },
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "3201907018807"
                },
                {
                    "name": "PS4",
                    "type": "command",
                    "value": "KEY_HDMI"
                },
                {
                    "name": "SledovaniTV",
                    "type": "app",
                    "value": "3202002020141"
                },
                {
                    "name": "YouTube",
                    "type": "app",
                    "value": "111299001912"
                }
            ],
            "keys": {
                "INFORMATION": "KEY_HOME"
            }
        }
    ]
} `

**Comment by tavicu** [comment]
Hi,

I'm sorry but i don't offer support for Hoobs. Other repored similar problems like yours with Hoobs. It could be because of writing permissions or hoobs remove the files when it restarts, i don't know. The plugin was developed for homebridge and not for hoobs :)

The plugin writes a json file where it stores the token once it was paired. That's why i say it may not have permissions to write this json or it removes the file when it restarts. Cause the plugin don't find the token and ask to pair again.

The fact that the name is changing, others reported this on hoobs, i don't know why! But it should not impact how the token is saved because the uuid is creaded from mac addres plus uuid field from config. As long as one of this don't change the name doesn't matter.

**Comment by Homekitdude** [comment]
Has anyone figured this out on HOOBS? This pop up makes the plugin unusable for me. Thanks so much
