### ISSUE TITLE
Power off not working as intended

### ISSUE THREAD

**Issue by rkhirata** [tavicu/homebridge-samsung-tizen#467]
Hello,

I have a Samsung Q6FN TV. Regarding the HomeBridge it is running on a Raspberry Pi3. Functions/Commands like Power On, sending strings of Commands through switches and other things all work fine via Home App on iPhone.

However, I am experiencing a issue. When the TV is Off, running a Scene with the TV Power Toggle set as Off, turns the TV On. This scene was configured to turn 3 devices off: Apple TV, HomePod Mini and the Samsung Q6FN TV. When the TV is On, this scene works as intended.

Can you help me with this issue?

Or help me with my goal: Make a scene inside Home App to turn these 3 devices Off.

I also tried creating a Switch with the Command KEY_POWEROFF, however it does not turn the TV Off.

Thanks in advance

**Comment by tavicu** [comment]
Hi,

Are you trying to run the scene after you just toggled the power from your remote?

Because the status of the TV is updated every 5 seconds by default and the Scene should not toggle or send any command if the TV is already OFF.

Also the plugin checks if the TV is OFF before sending the OFF command and if it's OFF then it will not send the command.

So the only reason explanation is that in the Home app (in the background) when it runs the scene it see the TV as ON.
