### ISSUE TITLE
Option to hide "Samsung Volume"

### ISSUE THREAD

**Issue by T-IOOO** [tavicu/homebridge-samsung-tizen#490]
I have Samsung Q70T together with this awsome plugin.
Everything is working just fine.

One thing that annoys me though is the "Samsung Volume" accessory that is shown in homebridge accessory list. I want to be able to hide it but it reappears all the time. Is it possible to maybe add an option for it to be hidden?
It's not showing up in the home app which is good.

**Comment by tavicu** [comment]
Hi,

Unfortunately at the moment there is no option to hide it from the plugin because that will means to remove the volume functionality.

But i checked Config UI X and there is an option that you can check to hide an accessory.
![Screen Shot 2022-03-08 at 10 47 51](https://user-images.githubusercontent.com/172068/157201760-0b836f01-5a77-4d0f-ac0d-f6eba753da29.png)

**Comment by T-IOOO** [comment]
Yes, I am aware of that option in homebridge. Only problem is that it will reappar every time homebridge is restarted. I have my volume controlled through apple tv and that volume accessory would be of no use for certain users. Therefore an option to hide it would be nice :)

**Comment by tavicu** [comment]
I'm sorry but this will not be implemented since it's a useful feature and your problem appears to be from Config UI X.

You could create a new room and drop everything you don't like over there or fork the plugin and remove the volume yourself (comment this line https://github.com/tavicu/homebridge-samsung-tizen/blob/master/lib/accessories/television.js#L43)
