### ISSUE TITLE
#390 this issue is back - MaxListenersExceededWarning

### ISSUE THREAD

**Issue by fate8383** [tavicu/homebridge-samsung-tizen#496]
I am having this issue after the last update, tried API set up, added few switches/inputs but then removed as i see no use for me. I still get this error:

(node:31744) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by tavicu** [comment]
Nothing was changed regarding the listeners since months ago.

Try to run in debug mode or with --trace-warnings on so we will see who trigger the warning.
I also find the `added to [Socket]` strange. It may be from another plugin and was just a coincidence with your added switches and inputs.

Cause at the moment you could add hundred of switches and inputs without affecting the listeners. There are no listeners initiated for switches and inputs.

**Comment by fate8383** [comment]
false alarm, i am sorry, another plugin causing this, added the trace in node and i can see clearly now.
