### ISSUE TITLE
UE55JS8000

### ISSUE THREAD

**Issue by benfysh** [tavicu/homebridge-samsung-tizen#5]
Hi, I have tried this plugin with my UE55JS8000 and the power switch appears in the Home app and reflects the state of the TV however when I toggle the switch it has not effect and will the revert back to the actual state of the TV.

I saw a similar closed issue #4 however my TV does not appear to have the _Settings - General - External Device Manager - Device List_ menu path.

**Comment by tavicu** [comment]
Hi, from what i've seen your TV doesn't have Tizen Operating System. 

Tizen looks like this: https://www.flatpanelshd.com/pictures/samsung2017smarttv-3.jpg

The plugin can see your tv if it's on or off because it's just checking to see if the IP address responds. But can't turn off the tv because it can't receive commands.

I will look to see if there is any api available to send commands for your TV. But it will be hard for me to test it since i don't have a TV with your operating system.

If i find an api available and you are willing to help me with testing we can try to make it work :)

**Comment by tavicu** [comment]
Hey @benfysh, sorry for late reply.
I had some problems and didn't had time to look for apis. I will search this week and come with a response of what i've found.

**Comment by benfysh** [comment]
No problem, thanks for letting me know :)

**Comment by tavicu** [comment]
@benfysh Hei. Sorry for the late response (it's been a very busy period for me).

I have looked over other repositories that are using Samsung api and all of them is using the same as me.

And unfortunately Samsung is not offering any information regarding the api :(

**Comment by benfysh** [comment]
No problem, thanks for looking its strange as the TV claims to be powered by Tizen. Who knew TV fragmentation was a thing!
