### ISSUE TITLE
'403 - Forbidden' when trying to switch to any input

### ISSUE THREAD

**Issue by mreassassin** [tavicu/homebridge-samsung-tizen#502]
I'm getting the Forbidden error when trying to set my TV's to any input (HDMI1, HDMI2, DigitalTV).

all apps work fine (Netflix, Disney+, HBOMax, YouTube etc.).

I triple checked all device ID's and even got a new API token.  Nothing seems to allow me the access to those inputs through homekit.

I'm on the latest version of the plugin.

thanks for all the hard work on creating and evolving this plugin!

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/SmartThings-Setup

You missed something from the documentation then. That's an error sent by SmartThings API meaning your api_key or device_id are wrong or you didn't give enough access on `Authorized Scopes`.

**Comment by mreassassin** [comment]
hmmm... not sure what it could be.  I've done the whole 'dance' 3 times now with the same results.  does it make sense that all other 'app inputs' work, just not the HDMI or Digital TV inputs?

**Comment by mreassassin** [comment]
yeah.  all of the tv's respond to the smartthings app just fine.  I'm able to turn them on/off, change sources and inputs etc.

**Comment by tavicu** [comment]
Other than that I don't know how to help you.

That error is from SmartThings API and it shows that it can authenticate with the `api_key` to the API but that key doesn't have access to the `device_id` you set.

**Comment by tavicu** [comment]
Hei,

At this point I will close the issue because I don't know how to help you.

The error is 100% from SmartThings API that is not able to access the device with the `api_key` and `device_id` from your config.

1. If you know you are using some firewall on your router to block internet access to your TV it may be that.
2. It may be because you didn't select all permissions when you created the `api_key`
3. It may be because your TV was unpaired from SmartThings. Samsung does this after 28 days without using the SmartThings App.
