### ISSUE TITLE
(Question) Tizen Browser with URL as Input? Move cursor command?

### ISSUE THREAD

**Issue by schrisander** [tavicu/homebridge-samsung-tizen#506]
Hi there

Sorry if this question has been asked before or explained somewhere else (I’ve tried to find it on google and github)

Do we have any method to call Tizen browser with specific URL as an input?

Can we move cursor to specific X & Y coordinates?

What I’m trying to do is opening a specific website (full screen), and move the cursor to the edge of screen. Combining these two commands as an input.

I’ve found these two methods available on other project for Samsung Tizen TV: https://github.com/xchwarze/samsung-tv-ws-api

Thank you

PS: Thanks for @tavicu making this great plugin!

**Comment by tavicu** [comment]
Hi @schrisander,

My plugin only supports to open browser.
That's because we are using another endpoint to open an application which from what i know it won't accept the url.

In the past we were using the same endpoint as samsung-tv-ws-api but some of the apps were not opening with that endpoint and we had to switch.

Regarding moving the cursor, the plugin doesn't support that.
