### ISSUE TITLE
HDMI4

### ISSUE THREAD

**Issue by Franco268** [tavicu/homebridge-samsung-tizen#509]
Hi,
I try to select HDMI4 by to ways, but without succes...
As an Input:
` { "type": "input", "name": "InputCam", "value": "HDMI4" }`
But that appears in home app like a status "activated" and an icone "Home"

and as a  switches
`{ "name": "Test Cam", "power": true, "input": "HDMI4" }`
That appears like a switch...nice. But the log mentionned "invalid device state"

Could you help me?

**Comment by tavicu** [comment]
Hei,

>  But that appears in home app like a status "activated" and an icone "Home"

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--inputs-are-appearing-like-separate-accessories

> and as a switches `{ "name": "Test Cam", "power": true, "input": "HDMI4" }` That appears like a switch...nice. But the log mentionned "invalid device state"

That means SmartThings API see your TV as off when it tried to send the command.
There are 2 possible options here:
1. Check if you can control the TV from the SmartThings app because Samsung unpair devices after 28 days of not using them with the app.
2. Your TV is older and needs more delay between powering on and accepting a command. You can change this delay with `wait_time`. It's value is represented in milliseconds, so 1000 means 1 second. By default it's set to 3000, you can try with 10000 (10 seconds) like this:
```
"devices": [
    {
        ...
        "wait_time": 10000
    }
]
```

**Comment by Franco268** [comment]
Thank you tavicu!

It was the case #1: device unpaired
