### ISSUE TITLE
Error: Command failed: ping -t 1 -c 1 [TV IP]  /  bad parameter [TV IP]

### ISSUE THREAD

**Issue by idanyc** [tavicu/homebridge-samsung-tizen#53]
I am running HomeBridge on Windows 10 (node.js v10.15.0) 
TV set is NU8000 firmware 1202
http://[TV IP]:8001/api/v2/ returns details successfully
TV doesn't show the pairing popup

homebridge -D returns: 
```
[1/29/2019, 9:40:57 PM] [TV] [DEBUG] Bad parameter [TV IP].

[1/29/2019, 9:40:57 PM] [TV] [DEBUG] { Error: Command failed: ping -t 1 -c 1 [TV IP]

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ping -t 1 -c 1 [TV IP]' }
```

manually running "ping -t 1 -c 1 [TV IP]:8001" also returns "Bad parameter [TV IP].", ping -t -c 1 [TV IP] (without "1" for -t) works fine

**Comment by idanyc** [comment]
Update: I manually edited the ping command SamsungRemote.js, to `ping -t -c 1 [TV IP] `,
now I can only turn **on** the TV (The TV still doesn't show the pairing popup)

**Comment by KYDronePilot** [comment]
I had a similar issue and updated the ping command to `ping -t 3 -c 1 [TV IP]`, which fixed the issue for me. There is currently a pull request open to fix this, but it has yet to be reviewed.

**Comment by idanyc** [comment]
@KYDronePilot it is not the same... for me i can't put any value after -t 
I am running it now with `ping -n 1 -c 1 [TV IP]`

I did manage to pair it with the tv - the problem was that I didn't realize the device name in the config file and in the TV itself have to match (maybe it is worth it to mention it common issues in readme) - after that i got the popup successfully

but it is working inconsistently

I start homebridge when tv is off
home app shows tv is on...
turn off > nothing happens 
turn on > it turns on
turn off > it turned off
ping still happens every 10 seconds idk if that is supposed to be like that or because i messed with the ping command
at some point the tv stops replying to ping and home app doesn't get statuses

[debug.txt](https://github.com/tavicu/homebridge-samsung-tizen/files/2814384/debug.txt)

**Comment by tavicu** [comment]
Hi. Maybe some of the parameters are not available on Windows.

I am working on a new version of the plugin and i want to change the method that is used to see if TV is online.

**Comment by greensouth** [comment]
A little question as it was pointed by another developer.

Does the socket needs to be opened and closed continuously? is it possible to let the socket open and close it only when powering off the tv, and ask for the socket status instead of pinging the tv? 

If it works, that would help removing the extra time until the TV stops returning the pings.

**Comment by tavicu** [comment]
Ping command is very fast. ~5ms to respond

**Comment by tavicu** [comment]
The new version i am working on will use a different method to check if TV is online.

But still, you will get the false positive because the TV will not turn OFF right away, it will go into a sleeping mode for ~15 seconds.

I have also checked the option to listen when the socket close but it will also close after the 15 seconds.

And the biggest problem for why i am closing the socket is because of the ultra mega shit that api it is. Less words, if the socket remains too much open or you have multiple sockets opened the API will freeze and not respond to anything even if you turn off and on the tv. You must hard reset it to work again ...
