### ISSUE TITLE
Channel changing issue

### ISSUE THREAD

**Issue by Robb007** [tavicu/homebridge-samsung-tizen#540]
Hi, my set top box is connected to HDMI1. Before smartthings integration the channel changing commands worked perfectly. When I was watching Live TV switches worked for Live TV channels, when I was watching STB they worked for satellite channels. Now the switches don't work for my STB. They send the channel number to my STB, but the TV is displaying the warning: "Channel not found (channel number). Try again". I tried with and without commands: power: true; input: hdmi1 - it doesn't make any difference. Inputs and volume controls works fine. Any ideas?

**Comment by tavicu** [comment]
Hi.

That's because the "old" method of changing channels was to send a list of commands. Example: channel 47 => KEY_4, KEY_7, KEY_ENTER
That's why it worked previously.

Now with SmartThings there is an api which we are using that changes the channel. And from what I know it's working only on Live TV.

At the moment there is no option to revert at the previous method, but I will add an option so it could be configured.

**Comment by Robb007** [comment]
I understand, thanks.

**Comment by tavicu** [comment]
> I understand, thanks.

Hi @Robb007, I was looking over this issue to implement a config but since you are the only one asking for this I would rather offer you an alternative.

I guess you are using a custom switch. Instead of setting the channel, send a list of commands like the old method used.

For example, from this:
`{"name": "Ch 13", "channel": 13}`
to this:
`{"name": "Ch 13", "command": ["KEY_1", "KEY_3", "KEY_ENTER"]}`

Let me know if that works for you!
