### ISSUE TITLE
Missing Keys for volume up/down buttons

### ISSUE THREAD

**Issue by Cristov9000** [tavicu/homebridge-samsung-tizen#559]
For the past three months, since install, using the control center remote I have been able to use the Volume up and down keys to control TV volume.  Two days ago this stopped working and the visual from the remote screen that shows the volume buttons are active disappeared.  I can remap the volume commands to the info button ("INFORMATION": "KEY_VOLUP") and that works but it seems that the mapping to the physical iPhone volume buttons has disappeared.  I can't find any documentation on how to map these side buttons again.  Using "VOLUME_UP": "KEY_VOLUP", "VOLUME_DOWN": "KEY_VOLDOWN" doesn't appear to work.

**Comment by tavicu** [comment]
Rrstart your phone

**Comment by tavicu** [comment]
> I restarted my phone about a dozen times and no change. The same thing happened to the Bravia plugin I am using and after I remapped the volume buttons they came back for control center remote when I select that TV.

The mapping have nothing to do with the problem, at least on my plugin. Because you cannot map the volume buttons, only the buttons from the screen.

HomeKit just sends the command for volume up/down and my plugin just execute commands.

Many other had this problem in the past but after a few restarts / a few days everything worked back. The problem it's on Apple side and there is nothing I can do unfortunately.
