### ISSUE TITLE
Volume increment

### ISSUE THREAD

**Issue by preamptive** [tavicu/homebridge-samsung-tizen#564]
Love this plug-in but have one small issue. Is there any way to make the volume go up in smaller increments? When using the HomeKit tv remote side volume buttons my volume goes too loud really quickly.
Doesn’t seem to be any way to change it on the tv so thought I’d see if it’s possible at this end.

**Comment by tavicu** [comment]
Hi, it's strange what you are telling because one push of the button = one command to increase/decrease volume with 1
Even if you hold the volume button pressed it will only trigger once.

At least on latest iOS release, i don't know if they changed anything with the new beta iOS.

You could start homebridge in debug mode and see what commands are sent when you push the button once.

**Comment by preamptive** [comment]
Thanks. I think it’s specific to my setup. Optical out from tv to amp. But there is no way to change the increment sent from the tv.
