### ISSUE TITLE
Exposing Motion Sensor in Samsung Frame TV 4K QLED LS03B Series

### ISSUE THREAD

**Issue by yasserabdalla** [tavicu/homebridge-samsung-tizen#646]
Is it possible to expose the motion sensor in Samsung Frame TV to HomeKit automation, this will be very useful to integrate with other home automation scenarios. For example, turning room lights off and on in synch with the frame picture when someone moves in or out of the room. 

Great plug in and thank you so much.

**Comment by guffelman** [comment]
I don't see anything relating to the motion sensor in the API docs, but it is certainly an interesting use case. If it were hypothetically available, it'd be something you'd have to subscribe to in order to get accurate notifications. See SimpliSafe's plugin for reference. Their motion sensors aren't something you can "subscribe" to, so you'd have to poll every x number of seconds (x being less than the rate limit of the API). This would imply that there is a possibility of missing motion events if they occur and conclude within the time interval between successive polling requests made at intervals of x seconds.

**Comment by tavicu** [comment]
Hi @yasserabdalla,

When it comes to apis Samsung is very restricted and they want to force you to use their App.

Until last year Samsung had an API for Frame TVs that provided instant updates regarding Art Mode. And they removed it ...

I would suggest getting a motion sensor, it's cheap and more reliable.
