### ISSUE TITLE
supportedPictureModes – only EyeComfort and Optimised

### ISSUE THREAD

**Issue by proandreyyy** [tavicu/homebridge-samsung-tizen#647]
Hi. 
I've been struggling for a long time with setting Switcher to switch Picture Mode - Dynamic/Standard.

However, after several hours of unsuccessful attempts, I found that you can look at STATUS (https://api.smartthings.com/v1/devices/deviceID/status), where you can also see all possible **supportedPictureModes**.... 

And here are mine (only two):
```
"custom.picturemode": {
    "pictureMode": {
        "value": "EyeComfort",
        "timestamp": "2023-09-18T19:16:46.513Z"
    },
    "supportedPictureModes": {
        "value": [
            "EyeComfort",
            "Optimised"
        ],
        "timestamp": "2023-09-18T19:16:46.513Z"
    },
    "supportedPictureModesMap": {
        "value": [
            {
                "id": "modeGen_589826",
                "name": "EyeComfort"
            },
            {
                "id": "modeIntelligent",
                "name": "Optimised"
            }
        ],
        "timestamp": "2023-09-18T19:16:46.513Z"
    }
},
``` 

What's my point? It might be useful to someone. I don't know why I don't have any other Picture Mode available. I have turned Intelligent Mode on and off, but I have not been able to add a switcher dynamic/standard.

**Possible improvement: add "EyeComfort" and "Optimised" picture modes to documentation.** 

Thank you!

**Comment by tavicu** [comment]
Hi @proandreyyy,

First time I hear about this. I would expect Standard and Dynamic to be on all TVs. But at this point nothing surprise me anymore from Samsung :P 

If i'm not mistaken when you try to set a picture mode that it's not available you will get an error message in the console that the mode is not available and a list with what mode the TV supports.

Adding "EyeComfort" and "Optimized" options in the dropdown will make users believe that mode should be available and it's a problem that they are not working. That's why only the most common modes are specified.

But even if they are not in the dropdown, you could set them manually in config file without problems.

**Comment by proandreyyy** [comment]
@tavicu I was getting the error "invalid device state", but it did not specify the cause or possible solutions. 

I would also like to mention that I have Intelligent Mode enabled on my TV, because of this I only have two modes available: Dynamic/Standard.

This issue is just an FYI :)

**Comment by tavicu** [comment]
Hi. I know this issue is old but I just want to mention that with the new v6 version (beta now) if you have SmartThings set up it will load the supported picture modes and display them in the interface when you add a switch for a device :)
