### ISSUE TITLE
On/off state does not update when using TV remote

### ISSUE THREAD

**Issue by slawnz** [tavicu/homebridge-samsung-tizen#649]
Have a QN90B that I have had working with the plugin for about 6 months on wifi with no issue. Changed from wifi to LAN connection, updated the MAC address in the plugin, also renewed API key. Controlling power state via Home app is fine, but the power state never updates in Home app when I use the TV remote. I use power state as a trigger to turn a subwoofer on/off so keen to fix this. Is there any known issue with wired connections? Thanks.

**Comment by tavicu** [comment]
Hi.

There is no difference between wifi or wired when it comes to the plugin.

If you want to make this change you need to:
- Assign a static IP address to the new mac on your router
- Remove TV from Home app
- Change the IP and MAC address in config file
- Restart Homebridge
- Add the TV to Home app and pair it

Each device have a unique ID (uuid) that it's created from MAC address. Changing the MAC address will basically create a new TV that's need to be added. That's why you need to do these steps.

**Comment by slawnz** [comment]
Thanks - that fixed it!
