### ISSUE TITLE
Issue - After TV is turned off status does not match for a couple of minutes in Home

### ISSUE THREAD

**Issue by frankb-CZ** [tavicu/homebridge-samsung-tizen#661]
When I turn off TV either via remote or via Apple Home it is shown as turned off but couple seconds later is is shown again as on but in reality it is still of. If I click it via Home to turn it off, TV turns on and status is exactly the opposite afterwards.

**Comment by tavicu** [comment]
What happens if you wait after you see it on? Let's say one minute? It will show as off eventually?

Probably you have an older TV that doesn't report the power state and when TV turns off is not actually of for around 15-30 seconds, it's in a sleep state.

> If I click it via Home to turn it off, TV turns on and status is exactly the opposite afterwards.

That's because the action you do in Home app it's not a direct command to turn on or off the TV. It's actually a toggle state.

**Comment by frankb-CZ** [comment]
Oh understood. Yeah if I wait for a minute or two the status actually shows as off after that. I have some automation based on that but probably I would need to find another input for them. Thanks for the answer. Have a good day

**Comment by tavicu** [comment]
Unfortunately Samsung don't provide a good API to control and get status of TVs.

Everything we do is by finding different paths and try to take advantage of them. Right now to check the TV state are three things that are done and they are not very accurate. Also some TVs respond different than others.

That's why I don't recommend making automations based on the state because it's not always accurate. Better getting a power plug that report power usage and make automations based on that. They are cheap and also help you see how much power your TV used :)

I am working on a new version of the plugin where I have found a possible more accurate option to check for the state, but same there, it will be a workaround, not something specific unfortunately.

**Comment by frankb-CZ** [comment]
Thanks man, I appreciate your work :) Take care, good luck in 2024
